### ISSUE TITLE
FR: configure ray cluster nodes for new cluster

### ISSUE THREAD

**Issue by paveldournov** [GoogleCloudPlatform/ai-infra-cluster-provisioning#34]
When the cluster is setup it has pre-installed Ray, but the cluster nodes are not configured. It requires manual configuration to make Ray recognize the cluster nodes.
Upon startup, the deployment tool should:
1) select a node for Ray master
2) create cluster config with all nodes included 
3) start the master Ray and worker Ray nodes
4) start the Ray dashboard, and map it to the inverse proxy to enable browsing
5) report to the user which node is the master and how to connect to the Ray dashboard and Ray client tools

**Comment by soumyapani** [comment]
#1, #2 and #3 from the ask is already supported. for mapping the dashboard to inverse proxy we need to have a server in the VM. More information will be added once the OKRs are clear.

**Comment by soumyapani** [comment]
Created issue #118 for providing access to Ray UI and telemetry dashboard.
