### ISSUE TITLE
[Suggestion] Enable GPU centric scale spec

### ISSUE THREAD

**Issue by paveldournov** [GoogleCloudPlatform/ai-infra-cluster-provisioning#5]
Instead of specifying the type of instances (which one needs to get a list of somewhere) and the count of GPUs per instance - enable the user to specify the number of GPUs and GPU types (which is known from NVIdia site, and can be documented here too). This way the user can simply specify the cluster size in terms of the GPU count, which is how typically users think about the scale. E.g. 16xA100, or 32xV100, etc. The count can be rounded up to the whole number of VMs.

**Comment by soumyapani** [comment]
GPUs are now determined based on the vm type https://cloud.google.com/compute/docs/gpus.
Supported in latest version of provisioning tool.
