### ISSUE TITLE
Add periodic test to validate cluster creation in develop branch.

### ISSUE THREAD

**Issue by soumyapani** [GoogleCloudPlatform/ai-infra-cluster-provisioning#79]
1. [Develop and test using terraform and cloud build](https://cloud.google.com/architecture/system-testing-cloud-functions-using-cloud-build-and-terraform)
2. [Using cloud build as a test runner](https://cloud.google.com/community/tutorials/cloudbuild-test-runner)

**Comment by stevenBorisko** [comment]
added in #91
