### ISSUE TITLE
Recreating a cluster fails to replace start up script

### ISSUE THREAD

**Issue by abdallag** [GoogleCloudPlatform/ai-infra-cluster-provisioning#84]
Version v0.3.0

Repro steps:
Create a cluster with start up command.
Delete MIG
Recreate the cluster with a different start up command.

Script doesn't run and I see the following error in serial console logs:

CommandException: No URLs matched: gs://vakuz-t5-pipeline-test/repro/repro-net-deployment/initializestartup.sh
Mar  3 22:56:37 repro-net-vm-6xl6 google_metadata_script_runner[804]: startup-script: Fri Mar 03 22:56:37 +0000 2023 Error [851]: gsutil reported non-zero exit code fetching gs://vakuz-t5-pipeline-test/repro/repro-net-deployment/initializestartup.sh.  Retrying (9/10)
Mar  3 22:56:37 repro-net-vm-6xl6 google_metadata_script_runner[804]: startup-script: Fri Mar 03 22:56:37 +0000 2023 Info [851]: === start executing runner: repro/repro-net-deployment/initializestartup.sh ===
Mar  3 22:56:37 repro-net-vm-6xl6 google_metadata_script_runner[804]: startup-script: chmod: cannot access '//tmp/initializestartup.sh': No such file or directory
Mar  3 22:56:37 repro-net-vm-6xl6 google_metadata_script_runner[804]: startup-script: Fri Mar 03 22:56:37 +0000 2023 Info [851]: === repro/repro-net-deployment/initializestartup.sh finished with exit_code=1 ===

**Comment by stevenBorisko** [comment]
@abdallag I cannot reproduce this after pulling the latest changes from `develop`. Are you still seeing this problem?

**Comment by soumyapani** [comment]
This is due to terraform bug that HPC toolkit team is trying to fix. For now Please run destroy, change startup script and then run create again.

**Comment by soumyapani** [comment]
Fix is implemented by HPC toolkit team. Reopening the bug to implement the right fix.
