### ISSUE TITLE
Some nodes on the cluster lose network connectivity after 1 hour

### ISSUE THREAD

**Issue by abdallag** [GoogleCloudPlatform/ai-infra-cluster-provisioning#85]
The latest image (v0.3.0) have a problem where we lose network connectivity after approximately 1 hour of cluster creation.

Here are the repro steps:

1. Create a cluster of 8 VMs or more. Here is a sample env.list we used:

PROJECT_ID=bct-staging-supercomputer
NAME_PREFIX=repro-net
ZONE=us-central1-a
ACCELERATOR_TYPE=nvidia-tesla-t4
VM_TYPE=n1-standard-16
TERRAFORM_GCS_PATH=gs://vakuz-t5-pipeline-test/repro
STARTUP_COMMAND=while true; do gcloud compute instances describe $(hostname) --zone=us-central1-a | grep status ; sleep 30; done
INSTANCE_COUNT=8
GPU_COUNT=1

2. Wait approximately 1 hour
3. Check the serial console of the machine. You will find at least 1 machine that lost network connectivity. Here are some of the errors that you will find on the serial console that indicate network connectivity loss:

bash[9736]: Exception found reporting metrics HTTPConnectionPool(host='metadata', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/attributes/proxy-mode (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe390514050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Mar  4 00:34:00 repro-net-vm-2tcl google_guest_agent[9761]: ERROR main.go:175 Network error when requesting metadata, make sure your instance has an active network and can reach the metadata server.
Mar  4 00:34:00 repro-net-vm-2tcl google_guest_agent[9761]: ERROR main.go:178 Error watching metadata: Get "http://169.254.169.254/computeMetadata/v1//?recursive=true&alt=json&wait_for_change=true&timeout_sec=60&last_etag=54db73eb2c545f4f": dial tcp 169.254.169.254:80: connect: network is unreachable
Mar  4 00:34:02 repro-net-vm-2tcl proxy-forwarding-agent[897]: 2023/03/04 00:34:02 Failed to read pending requests: "A proxy request failed: \"Get \\\"https://us-central1.notebooks.cloud.google.com/tun/m/4592f092208ecc84946b8f8f8016274df1b36a14/agent/pending\\\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)\""

**Comment by soumyapani** [comment]
Investigated this issue further. 
We are using `nic_type` as `GVNIC` and it looks like debian 10 does not support GVNIC. [Reference](https://cloud.google.com/compute/docs/images/os-details#networking)

We are using DLVm images and there is no debian 11 DLVM images yet
```
gcloud compute images list --project ml-images | grep "debian-11"
WARNING: Could not setup log file in /usr/local/google/home/soumyapani/.config/gcloud/logs, (PermissionError: [Errno 13] Permission denied: '/usr/local/google/home/soumyapani/.config/gcloud/logs/2023.03.08/22.48.37.861059.log'.
The configuration directory may not be writable. To learn more, see https://cloud.google.com/sdk/docs/configurations#creating_a_configuration
debian-11-bullseye-arm64-v20230306                      debian-cloud         debian-11-arm64                                READY
debian-11-bullseye-v20230306                            debian-cloud         debian-11                                      READY
debian-11-tf-2-12-0-v20230308                           ml-images            tf-2-12-0                                      READY
``` 

I have verified following [this method](https://cloud.google.com/compute/docs/networking/using-gvnic#verify-gvnic) and looks like DLVM debian-10 image is actually missing GVNIC.
![image](https://user-images.githubusercontent.com/112522451/223874998-6d778096-4f2e-41b3-b0d6-9afdb35528a9.png)

But DLVM team says that GVNIC is supported on [all DLVM images](https://cloud.google.com/deep-learning-vm/docs/release-notes#February_19_2021).
